import { escapeHtml, slugWords, titleCase } from './utils.js';
import { normalizeAddress, hardenPagePayload } from './html.js';

function baseCss() {
  return `:root{color-scheme:light;font-family:Arial,"Segoe UI",Roboto,sans-serif;--text:#202124;--muted:#5f6368;--line:#dadce0;--soft:#f8fafd;--blue:#1a73e8;--green:#188038;--red:#d93025;--yellow:#fbbc04;--shadow:0 1px 2px rgba(60,64,67,.12),0 8px 28px rgba(60,64,67,.10)}*{box-sizing:border-box}html,body{margin:0;min-height:100%;background:#fff;color:var(--text)}a{color:inherit}button,input,select{font:inherit}.top{height:56px;display:flex;align-items:center;gap:18px;padding:0 26px;border-bottom:1px solid #edf0f2;background:rgba(255,255,255,.94);backdrop-filter:blur(12px)}.top a{text-decoration:none;color:#3c4043;font-size:14px}.brand{display:flex;align-items:center;gap:10px;font-weight:700}.mark{width:26px;height:26px;display:grid;place-items:center;border-radius:8px;background:#111;color:#fff;font:700 14px/1 ui-monospace,SFMono-Regular,Consolas,monospace;box-shadow:inset 0 0 0 1px rgba(255,255,255,.14)}.mark:before{content:"/>";letter-spacing:-.12em;transform:translateX(-1px)}.spacer{flex:1}.search{display:flex;align-items:center;gap:10px;width:min(680px,100%);min-height:46px;padding:0 16px;border:1px solid #dfe1e5;border-radius:999px;background:#fff;box-shadow:0 1px 6px rgba(32,33,36,.12)}.search input{flex:1;min-width:0;border:0;outline:0;background:transparent;font-size:16px}.search button{border:0;background:#1a73e8;color:#fff;border-radius:999px;min-height:34px;padding:0 15px;font-weight:600}.chiprow{display:flex;gap:10px;flex-wrap:wrap}.chip{display:inline-flex;align-items:center;min-height:34px;padding:0 13px;border-radius:999px;background:#f1f3f4;text-decoration:none;color:#3c4043;font-weight:600;font-size:13px}.chip.blue{background:#e8f0fe;color:#174ea6}.chip.green{background:#e6f4ea;color:#137333}.chip.yellow{background:#fef7e0;color:#a14200}.card{border:1px solid #edf0f2;border-radius:18px;background:#fff;box-shadow:0 1px 2px rgba(60,64,67,.08);overflow:hidden}.card.pad{padding:18px}.card h2,.card h3{font-weight:500;letter-spacing:-.02em}.muted{color:#5f6368}.footer{padding:30px;text-align:center;color:#70757a;font-size:13px}`;
}

export function makeBuiltInPage(address) {
  const normalized = normalizeAddress(address);
  if (normalized === 'synthetic://home') return makeHomePage(normalized);
  return null;
}

export function makeHomePage(address = 'synthetic://home') {
  const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>New Tab</title><style>${baseCss()}body{display:grid;grid-template-rows:auto 1fr}.home{display:grid;place-items:center;padding:8vh 24px 40px}.wrap{width:min(760px,100%);display:grid;justify-items:center;gap:28px}.logo{font-size:clamp(64px,12vw,104px);line-height:.9;font-weight:700;letter-spacing:-.07em}.logo span:nth-child(1){color:#4285f4}.logo span:nth-child(2){color:#ea4335}.logo span:nth-child(3){color:#fbbc04}.logo span:nth-child(4){color:#4285f4}.logo span:nth-child(5){color:#34a853}.logo span:nth-child(6){color:#ea4335}.logo span:nth-child(7){color:#4285f4}.shortcuts{width:min(620px,100%);display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-top:6px}.shortcut{min-height:96px;display:grid;place-items:center;gap:10px;text-decoration:none;color:#3c4043;border-radius:16px}.shortcut:hover{background:#f8fafd}.shortcut b{width:46px;height:46px;border-radius:50%;display:grid;place-items:center;background:#f1f3f4;color:#1a73e8}.shortcut span{font-size:13px;text-align:center}@media(max-width:620px){.shortcuts{grid-template-columns:repeat(2,1fr)}.search{min-height:44px}.search button{display:none}}</style></head><body><header class="top"><a href="synthetic://home" class="brand"><span class="mark"></span><span>Slopweb</span></a><span class="spacer"></span><a href="synthetic://mail">Mail</a></header><main class="home"><section class="wrap"><h1 class="logo" aria-label="Slopweb"><span>S</span><span>l</span><span>o</span><span>p</span><span>w</span><span>e</span><span>b</span></h1><form class="search" action="synthetic://search" method="get"><span aria-hidden="true">⌕</span><input name="q" autofocus placeholder="Search or type a synthetic address"><button>Search</button></form><nav class="shortcuts"><a class="shortcut" href="synthetic://news/world-wire"><b>N</b><span>World Wire</span></a><a class="shortcut" href="synthetic://app/personal-dashboard"><b>D</b><span>Dashboard</span></a><a class="shortcut" href="synthetic://game/neon-maze"><b>G</b><span>Neon Maze</span></a></nav></section></main></body></html>`;
  return hardenPagePayload({ title: 'New Tab', summary: 'Slopweb home page.', html, model: 'built-in compiler' }, address);
}

export function makeLocalGeneratedPage(address, history = [], reason = '') {
  const normalized = normalizeAddress(address);
  const topic = slugWords(normalized, 'generated page');
  const title = titleCase(topic);
  const encodedTopic = encodeURIComponent(topic);
  const cards = [
    ['Explore', 'A clean overview with useful next steps.', `synthetic://result/${encodedTopic}/overview`],
    ['Board', 'A visual workspace with generated panels and controls.', `synthetic://board/${encodedTopic}`],
    ['Dashboard', 'Metrics, filters, and panels rendered for this address.', `synthetic://app/${encodedTopic}/dashboard`],
    ['Guide', 'A practical guide page with sections and details.', `synthetic://guide/${encodedTopic}`]
  ];
  const cardHtml = cards.map(([name, desc, href], index) => `<a class="tile" href="${escapeHtml(href)}"><span>${index + 1}</span><h2>${escapeHtml(name)}</h2><p>${escapeHtml(desc)}</p></a>`).join('');
  const historyHtml = Array.isArray(history) && history.length ? history.slice(-5).map(item => `<li>${escapeHtml(item)}</li>`).join('') : '<li>No recent path yet.</li>';
  const reasonHtml = reason ? `<details class="debug"><summary>Why local fallback rendered</summary><pre>${escapeHtml(reason).slice(0, 1600)}</pre></details>` : '';
  const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${escapeHtml(title)}</title><style>${baseCss()}.page{max-width:1180px;margin:0 auto;padding:34px 24px 60px;display:grid;grid-template-columns:minmax(0,1fr) 320px;gap:32px}.hero{padding:32px;border:1px solid #edf0f2;border-radius:28px;background:linear-gradient(135deg,#fff,#f8fafd);box-shadow:var(--shadow)}.hero h1{margin:0;font-size:clamp(38px,7vw,72px);line-height:.95;letter-spacing:-.06em;font-weight:500}.hero p{color:#4d5156;line-height:1.62}.tiles{display:grid;grid-template-columns:repeat(2,1fr);gap:16px;margin-top:18px}.tile{min-height:150px;padding:18px;border:1px solid #edf0f2;border-radius:18px;text-decoration:none;color:var(--text);background:#fff;box-shadow:0 1px 2px rgba(60,64,67,.08)}.tile span{display:inline-grid;place-items:center;width:34px;height:34px;border-radius:10px;background:#e8f0fe;color:#174ea6;font-weight:700}.tile h2{margin:16px 0 8px}.tile p{margin:0;color:#5f6368;line-height:1.55}.side{display:grid;gap:16px;align-self:start}.history{margin:0;padding:18px 18px 18px 34px;color:#5f6368;line-height:1.6}.debug pre{white-space:pre-wrap;max-height:220px;overflow:auto;color:#a50e0e}.debug{grid-column:1/-1;border:1px solid #edf0f2;border-radius:16px;padding:14px;background:#f8fafd}@media(max-width:860px){.page{grid-template-columns:1fr}.tiles{grid-template-columns:1fr}}</style></head><body><header class="top"><a class="brand" href="synthetic://home"><span class="mark"></span><span>Generated</span></a><form class="search" action="synthetic://search" method="get"><input name="q" value="${escapeHtml(topic)}"><button>Search</button></form><span class="spacer"></span></header><main class="page"><section><div class="hero"><p class="muted">${escapeHtml(normalized)}</p><h1>${escapeHtml(title)}</h1><p>This fallback page rendered because generation could not finish.</p><div class="chiprow"><a class="chip blue" href="synthetic://result/${encodedTopic}/deep-dive">Deep dive</a><a class="chip" href="synthetic://search/${encodedTopic}%20examples">Examples</a></div></div><div class="tiles">${cardHtml}</div></section><aside class="side"><section class="card"><h2 style="padding:18px 18px 0;margin:0">Recent path</h2><ol class="history">${historyHtml}</ol></section></aside>${reasonHtml}</main></body></html>`;
  return hardenPagePayload({ title, summary: `Generated local page for ${normalized}.`, html, model: reason ? 'local fallback compiler' : 'local compiler' }, normalized);
}
